apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
spec:
  volumes:
    - name: shared-storage
      persistentVolumeClaim:
        claimName: storage-shared-claim
    - name: worker-storage
      persistentVolumeClaim:
        claimName: storage-worker-claim
  containers:
    - name: storage-container
      image: ubuntu
      command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
      volumeMounts:
        - mountPath: "/data/shared"
          name: shared-storage
        - mountPath: "/data/worker"
          name: worker-storage
# attach this pod to the controller (we have no workers!)
  nodeSelector:
    "controller": "true"