apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-shared-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # shared is mounted shared across all workers
    path: "/mnt/shared"
