# https://humanitec.com/blog/handling-environment-variables-with-kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  # echo -n "appuser" | base64
  POSTGRES_USER: YXBwdXNlcg==
  # echo -n "secret" | base64
  POSTGRES_PASSWORD: c2VjcmV0